name: Azure Deploy

on:
  push:
    branches:
    - main
    
    paths:
        - 'generate-url-shortene/infrastructure/**'
  pull_request:
    paths:
      - 'generate-url-shortene/infrastructure/**'
  workflow_dispatch: # Allows you to run the workflow manually
 
permissions:
    id-token: write
    contents: read  

jobs:
  deploy-dev:
    runs-on: ubuntu-latest
    environment: development
    steps:
      - uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v2.1.0
        with:
          creds: '{"clientId":"${{ secrets.AZURE_CLIENT_ID }}","clientSecret":"${{ secrets.AZURE_CLIENT_SECRET }}","subscriptionId":"${{ vars.AZURE_SUBSCRIPTION_ID }}","tenantId":"${{ secrets.AZURE_TENANT_ID }}"}'


    
      - uses: azure/CLI@v2
        with:
          inlineScript: |
            #!/bin/bash
            az group create --name ${{ vars.RESOURCE_GROUP_NAME }} --location ${{ vars.RESOURCE_GROUP_LOCATION }}
            echo "Resource Group Created"

      - name: Deploy
        uses: azure/arm-deploy@v2
        with: 
          scope: 'Resource Group'   
          resourceGroupName: ${{ vars.RESOURCE_GROUP_NAME }}
          template: generate-url-shortene/infrastructure/main.bicep