name: Azure Deploy

on:
  push:
    branches:
      - main
    paths:
      - 'generate-url-shortene/infrastructure/**'
  pull_request:
    paths:
      - 'generate-url-shortene/infrastructure/**'
  workflow_dispatch: # Allows you to run the workflow manually

permissions:
  id-token: write
  contents: read

jobs:
  deploy-dev:
    runs-on: ubuntu-latest
    environment: development
    steps:
      - uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v2.2.0
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - uses: azure/CLI@v2.1.0
        with:
          inlineScript: |
            #!/bin/bash
            az group create --name ${{ vars.RESOURCE_GROUP_NAME }} --location ${{ vars.RESOURCE_GROUP_LOCATION }}
            echo "Resource Group Created"

      - name: Deploy Bicep Template
        uses: azure/arm-deploy@v2
        with:
          scope: resourcegroup
          resourceGroupName: ${{ vars.RESOURCE_GROUP_NAME }}
          template: ./infrastructure/main.bicep
          failOnStdErr: true